### ISSUE TITLE
Exception when response body is empty

### ISSUE THREAD

**Issue by mikes222** [jonsaw/amazon-cognito-identity-dart#10]
Simple testprogram (even without changing the user pool id):

    import 'package:amazon_cognito_identity_dart/cognito.dart';
    import 'package:flutter_test/flutter_test.dart';

    final userPool = new CognitoUserPool(
        'ap-southeast-1_xxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxxxxxxx');
    final userAttributes = [
      new AttributeArg(name: 'first_name', value: 'Jimmy'),
      new AttributeArg(name: 'last_name', value: 'Wong'),
    ];

    void main() {
      testWidgets('Amazon Cognito signup-test', (WidgetTester tester) async {
        var data = await userPool.signUp('email@inspire.my', 'Password001',
            userAttributes: userAttributes);
      });
    }

The system responds with the followin stacktrace:

Unexpected end of input (at character 1)

^

When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1362:5)
#1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:506:7)
#2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
#3      JsonDecoder.convert (dart:convert/json.dart:542:36)
#4      JsonCodec.decode (dart:convert/json.dart:169:41)
#5      Client.request (package:amazon_cognito_identity_dart/src/client.dart:50:23)
<asynchronous suspension>
#6      CognitoUserPool.signUp (package:amazon_cognito_identity_dart/src/cognito_user_pool.dart:95:34)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///E:/develop/flutter_testapp/flutter_testapp/test/cognito_test.dart:14:31)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:63:25)
...

Though the solution is obvious I think a better/tailored exception is preferred since such error may also occur in production if the systems are for example overloaded.

**Comment by jonsaw** [comment]
For some strange reason, `WidgetTester` is returning a blank JSON body.  Running the example app in Flutter or with Dart's test suite we gives us the following:

```
{__type: ResourceNotFoundException, message: User pool client xxxxxxxxxxxxxxxxxxxxxxxxxx does not exist.}
```

Anyway, better client request error handling is fixed in v0.0.16. Thanks for the suggestion.
