### ISSUE TITLE
Appsync examples

### ISSUE THREAD

**Issue by sweepy84** [jonsaw/amazon-cognito-identity-dart#11]
Wondering if you had more Appsync examples with offline data usage.

**Comment by jonsaw** [comment]
AppSync offline data will likely be beyond the scope of this package. However, will definitely post something in the community in the near future when I have a working example.

For AppSync to work well, we'll need the following:
- **Offline Storage**: can be solved today with an SQLite implementation
- **Real Time** MQTT messaging over WebSockets

#8
