### ISSUE TITLE
Http Browser Client

### ISSUE THREAD

**Issue by tskinn** [jonsaw/amazon-cognito-identity-dart#20]
Is it just me or am I kind of stuck using the io http client?

I am trying to utilize this package in an angulardart app but I get this error when instantiating a CognitoUserPool object:

```
EXCEPTION: Unsupported operation: Platform._version
STACKTRACE: 
dart:sdk_internal                                                          new
package:http/src/io_client.dart 23:56                                      new
package:http/src/client.dart 30:23                                         new
package:amazon_cognito_identity_dart/src/client.dart 24:26                 new
package:amazon_cognito_identity_dart/src/cognito_user_pool.dart 36:14      new
package:angular_app/src/core/cognito/cognito_service.dart 20:14            new
```
I believe this error is a consequence of using the http client in the browser. The Client class allows for injecting the http.Client into it, but the CognitoUserPool does not have a constructor that allows injection of the Client. It is possible to change the client after instantiation but then I would always get this error. Should I make a pull request with that capability?

**Comment by jonsaw** [comment]
Hey @tskinn, if you have a PR ready, I'll be glad to take a look!

**Comment by tskinn** [comment]
Not necessary any more since http package has been updated.
