### ISSUE TITLE
Has an error "NotAuthorizedException"

### ISSUE THREAD

**Issue by Den-Ree** [jonsaw/amazon-cognito-identity-dart#23]
Hello @jonsaw ! 
At first, thank for your package. 

I'm trying to use it on my project, where I use AWS Cognito. There are 2 apps: iOS native and Flutter. In  an iOS app with native SDK everything works, but in the Flutter one, I always have the error:
_CognitoClientException{statusCode: 400, code: NotAuthorizedException, name: NotAuthorizedException, message: Unable to verify secret hash for client `client_id`}_

Credentials are the same on both app (cliendID, pool id and etc).

**Comment by pmachan** [comment]
Hello @jonsaw
I have same problem as @Den-Ree

**Comment by Den-Ree** [comment]
@pmachan I have fixed it, using instead of iOS client_id, JS client_id.

**Comment by pmachan** [comment]
> @pmachan I have fixed it, using instead of iOS client_id, JS client_id.

What you mean? I have only **App client id** in my User pool, which is not specified for a particular platform.

**Comment by jonsaw** [comment]
Sorry for the late reply. You will have to follow the setup according to this [tutorial in Serverless Stack](https://serverless-stack.com/chapters/create-a-cognito-user-pool.html) to get it to work properly. I'll try to come up with proper Cognito setup documentation when I have more time.

**Comment by Den-Ree** [comment]
@jonsaw thanks, I will close it.
