### ISSUE TITLE
 http version 0.12.0

### ISSUE THREAD

**Issue by msaliminia** [jonsaw/amazon-cognito-identity-dart#24]
After upgrading flutter, I am getting the following error:

Because every version of flutter_test from sdk depends on http 0.12.0 and every version of amazon_cognito_identity_dart depends on http ^0.11.3, flutter_test from sdk is incompatible with amazon_cognito_identity_dart.

**Comment by jeprojects** [comment]
@jonsaw 

Can your merge this pull request and release another version?

https://github.com/jonsaw/amazon-cognito-identity-dart/pull/26

**Comment by jonsaw** [comment]
Working on it!

**Comment by jonsaw** [comment]
Deployed in v0.0.19
