### ISSUE TITLE
awsSig4 serviceName value/Unable to parse JWT token.

### ISSUE THREAD

**Issue by idkjs** [jonsaw/amazon-cognito-identity-dart#25]
@jonsaw great demo. Thanks for sharing.

I'm trying to call APPSYNC using this package in the example project. I'm guided by the example Appsync use case in @ncb000gt pull request.

Below is the `UserService` method in the `UserService` class modified. It throws the following error when I run it.
```s
I/flutter (26309): {
I/flutter (26309):   "errors" : [ {
I/flutter (26309):     "errorType" : "UnauthorizedException",
I/flutter (26309):     "message" : "Unable to parse JWT token."
I/flutter (26309):   } ]
I/flutter (26309): }
```

```dart
  Future<UserService> _getValues(BuildContext context) async {
    try {
      await _userService.init();
      _isAuthenticated = await _userService.checkAuthenticated();
      if (_isAuthenticated) {
        // get user attributes from cognito
        _user = await _userService.getCurrentUser();

        // get session credentials
        final credentials = await _userService.getCredentials();
        _awsSigV4Client = new AwsSigV4Client(
            credentials.accessKeyId, credentials.secretAccessKey, _endpoint,
            region: _region,
            sessionToken: credentials.sessionToken,
            serviceName: 'AMAZON_COGNITO_USER_POOLS');

        // get previous count
        _citiesService = new CitiesService(_awsSigV4Client);
        _cities = await _citiesService.getCities();
        // _counterService = new CounterService(_awsSigV4Client);
        // _counter = await _counterService.getCounter();
      }
      return _userService;
    } on CognitoClientException catch (e) {
      if (e.code == 'NotAuthorizedException') {
        await _userService.signOut();
        Navigator.pop(context);
      }
      throw e;
    }
  }
```

In javascript aws-sdk the params we have to pass are:
https://github.com/dabit3/appsync-react-native-with-user-authorization/blob/b312924fe57e0936186b4688d7c856b13e76c27b/App.js#L30-L37

```js
const client = new Client({
  url: AppSync.graphqlEndpoint,
  region: AppSync.region,
  auth: {
    type: 'AMAZON_COGNITO_USER_POOLS',
    jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken(),
  }
});
```
I'm thinking that solution is to pass `AMAZON_COGNITO_USER_POOLS` to `awsSigV4Client` some way. Any ideas on how to do this correctly?

Thank you.

**Comment by jonsaw** [comment]
In your AppSync Settings, can you try using Authorization Type: Amazon Cognito User Pool.

<img width="1443" alt="Screenshot 2019-03-12 at 11 36 05 AM" src="https://user-images.githubusercontent.com/1572333/54173241-206c0000-44bc-11e9-98cc-f2747bb30298.png">

Make sure to allow AppSync in your IAM user role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:ap-southeast-1:000000000000:apis/xxxxappsyncxapixidxxxxxxxx/*"
                //                               ^ Account ID          ^ API ID
            ]
        }
    ]
}
```

**Comment by arunpkumar92** [comment]
Hi @jonsaw ,

  This is great and it is worked for me. 

I have doubt I have a flutter application and I need login only some areas. Remain area how I fetch data from appSync using unauthenticated.

and we hardcoding user name and password with in the app is not good, right?

Please help me on this.
