### ISSUE TITLE
Incompatiable with current version 

### ISSUE THREAD

**Issue by shojibur** [jonsaw/amazon-cognito-identity-dart#27]
Was trying to add this package in my project and it showing following error: 

The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because every version of flutter_test from sdk depends on package_resolver 1.0.2 which depends on http ^0.11.0, every version of flutter_test from sdk requires http ^0.11.0.
And because amazon_cognito_identity_dart >=0.0.19+2 depends on http ^0.12.0 and amazon_cognito_identity_dart >=0.0.19 <=0.0.19+1 requires SDK version >=2.1.0-dev.8.0 <3.0.0, flutter_test from sdk is incompatible with amazon_cognito_identity_dart >=0.0.19.
So, because flutter_app_aws_signup depends on both amazon_cognito_identity_dart ^0.0.19 and flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by jonsaw** [comment]
Hi @shojibur, thanks for the feedback. I'll look into it.
