### ISSUE TITLE
Logged in user not being saved to storage

### ISSUE THREAD

**Issue by bbradley72** [jonsaw/amazon-cognito-identity-dart#28]
I am new to flutter and am trying to get my application integrated with aws cognito.

I took your example main.dart file and replaced the following code in the login screen class (sending the user to a new screen instead of displaying the snackbar message. I tested with the message and it does display I am logged in.

/**
    final snackBar = new SnackBar(
      content: new Text(message),
      action: new SnackBarAction(
        label: 'OK',
        onPressed: () {
          if (signUpSuccess) {
            Navigator.pop(context);
            if (!_user.confirmed) {
              Navigator.push(
                context,
                new MaterialPageRoute(
                    builder: (context) =>
                    new ConfirmationScreen(email: _user.email)),
              );
            }
          }
        },
      ),
      duration: new Duration(seconds: 30),
    );

    Scaffold.of(context).showSnackBar(snackBar);
**/
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => SecondScreen()),
    );

On the second screen, I moved the copied the code from the _SecureCounterScreenState class in the main.dart example file to build my own screen:

class _SecondScreenState extends State<SecondScreen> {
  final _userService = new UserService(userPool);
  User _user = new User();
  bool _isAuthenticated = false;
  CognitoUser _cognitoUser;

  Future<UserService> _getValues(BuildContext context) async {
    try {
      await _userService.init();
      _isAuthenticated = await _userService.checkAuthenticated();
      if (_isAuthenticated) {
        // get user attributes from cognito
        _user = await _userService.getCurrentUser();
        _cognitoUser = await _userService.getCognitoUser();

        // get session credentials
        final credentials = await _userService.getCredentials();
      }
      return _userService;
    } on CognitoClientException catch (e) {
      if (e.code == 'NotAuthorizedException') {
        await _userService.signOut();
        Navigator.pop(context);
      }
      throw e;
    }
  }

  @override
  Widget build(BuildContext context) {
    final f = new DateFormat.yMMMMd("en_US");

    return new FutureBuilder(
        future: _getValues(context),
        builder: (context, AsyncSnapshot<UserService> snapshot) {
          //if (snapshot.hasData) {
            //if (!_isAuthenticated) {
            //  return new LoginScreen();
            //}

            return new Scaffold(
              appBar: AppBar(
                title: Text(f.format(new DateTime.now())),
                backgroundColor: Color.fromARGB(255, 234, 100, 34),
              ),
              body: new Container(
                decoration: new BoxDecoration(
                  color: Color.fromARGB(255, 212, 43, 63),
                ),
                child: _cognitoUser == null
                    ? Container(
                  child: Text("null"),
                )
                    : Container(
                  child: Text(_cognitoUser.getUsername()),
                ),
              ),
            );
          //};
        }
    );
  }
}

If I uncomment this code:
if (snapshot.hasData) {
            //if (!_isAuthenticated) {
            //  return new LoginScreen();
            //}

I receive a builder returned null error.
With it commented out, _cognitoUser == null

Can you help me understand what I am doing wrong?

I am trying to use the login screen, then send the user to a second screen that uses displays the cognito user's username. The storage doesn't seem to be either saving or retrieving the user properly.

Thanks for your help

**Comment by jonsaw** [comment]
Hi @bbradley72, can you help to format the code? Cheatsheet [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting). It's a bit hard to read at the moment. Thanks.

**Comment by bbradley72** [comment]
Sorry, I should have previewed it before I submitted. Thanks for your help.

I am new to flutter and am trying to get my application integrated with aws cognito.

I took your example main.dart file and replaced the following code in the login screen class (sending the user to a new screen instead of displaying the snackbar message. I tested with the snackbar message and it does display I am logged in.

```
/**
final snackBar = new SnackBar(
	content: new Text(message),
	action: new SnackBarAction(
	label: 'OK',
	onPressed: () {
		if (signUpSuccess) {
			Navigator.pop(context);
			if (!_user.confirmed) {
				Navigator.push(
					context,
					new MaterialPageRoute(
						builder: (context) => new ConfirmationScreen(email: _user.email)),
					);
				}
			}
		},
	),
	duration: new Duration(seconds: 30),
);

Scaffold.of(context).showSnackBar(snackBar);
**/
```
```
Navigator.push(
	context,
	MaterialPageRoute(builder: (context) => SecondScreen()),
);
```
On the second screen, I moved the copied the code from the _SecureCounterScreenState class in the main.dart example file to build my own screen:

```
class _SecondScreenState extends State {
	final _userService = new UserService(userPool);
	User _user = new User();
	bool _isAuthenticated = false;
	CognitoUser _cognitoUser;

	Future _getValues(BuildContext context) async {
		try {
			await _userService.init();
			_isAuthenticated = await _userService.checkAuthenticated();
			if (_isAuthenticated) {
				// get user attributes from cognito
				_user = await _userService.getCurrentUser();
				_cognitoUser = await _userService.getCognitoUser();

    			// get session credentials
    			final credentials = await _userService.getCredentials();
  			}
  			return _userService;
		} on CognitoClientException catch (e) {
  			if (e.code == 'NotAuthorizedException') {
    			await _userService.signOut();
    			Navigator.pop(context);
  			}
  			throw e;
		}
	}

	@override
	Widget build(BuildContext context) {
		final f = new DateFormat.yMMMMd("en_US");

		return new FutureBuilder(
	    	future: _getValues(context),
	    	builder: (context, AsyncSnapshot<UserService> snapshot) {
	     	 	//if (snapshot.hasData) {
	        		//if (!_isAuthenticated) {
	        			//  return new LoginScreen();
 	       			//}

 	       			return new Scaffold(
          				appBar: AppBar(
            				title: Text(f.format(new DateTime.now())),
	            			backgroundColor: Color.fromARGB(255, 234, 100, 34),
    	      			),
        	  			body: new Container(
            				decoration: new BoxDecoration(
              				color: Color.fromARGB(255, 212, 43, 63),
	            		),
    	        		child: _cognitoUser == null
        	        		? Container(
            	  				child: Text("null"),
            				)
                			: Container(
          	    				child: Text(_cognitoUser.getUsername()),
            				),
          				),
	        		);
    	  		//};
    		}
		);
	}
}
```
If I uncomment this code:
```
if (snapshot.hasData) {
//if (!_isAuthenticated) {
	// return new LoginScreen();
//}
```

I receive a builder returned null error.
With it commented out, _cognitoUser == null

Can you help me understand what I am doing wrong?
I'm basically just testing the storage of the cognito user using this code, but it always is displaying null on the second screen. Once I figure that out, I should be able to the JWT token and make my API calls to lambda.

```
child: _cognitoUser == null
	? Container(
		child: Text("null"),
	)
	: Container(
		child: Text(_cognitoUser.getUsername()),
	),
),
```

I am trying to use the login screen, then send the user to a second screen that uses displays the cognito user's username. The storage doesn't seem to be either saving or retrieving the user properly.

Thanks for your help

**Comment by bbradley72** [comment]
Hi Jon,

I think I solved the issue. I had moved the signupscreens and userservice to their own files and imported them into main.dart using a relative path. Apparently, you have to use package:my_package_name/filename.dart in main or things don't work properly.

See this defect:
https://github.com/dart-lang/sdk/issues/33076

I changed:
import 'constants.dart';
import 'signupscreen.dart';
import 'userservice.dart';

to:
import 'package:my_package_name/constants.dart';
import 'package:my_package_name/signupscreen.dart';
import 'package:my_package_name/userservice.dart';

now when i proceed to the secondscreen, it displays my username as expected.

This also worked when I closed the app and restarted it.
It appears my issue was a dart defect unrelated to this code.
I'm going to close this issue.

Thanks for helping me. Sorry for the newbie question, this is my first flutter/dart project.
