### ISSUE TITLE
DynamoDB Setup

### ISSUE THREAD

**Issue by bretmh** [jonsaw/amazon-cognito-identity-dart#42]
How should our DynamoDB be setup?

My understanding is that you have a couple of lambda's setup working with the DynamoDB.

Currently I have a table made named "users" with a primary key of "email". Figured it be the most proper setup.

Does anyone have additional information on the prerequisites for the example app?

**Comment by bretmh** [comment]
just noticed the example server..

**Comment by cholojuanito** [comment]
@bretmh then I recommend closing the issue so the issues page doesn't fill up with forgotten issues
