### ISSUE TITLE
Logged in user does not persist in storeage

### ISSUE THREAD

**Issue by CtrlAltDft** [jonsaw/amazon-cognito-identity-dart#45]
Whenever i log in an user with authenticateUser(), I can get the user's info by calling getCurrentUser() as long as the app is still running. However, when the app is relaunched, getCurrentUser() will always return null and thus user will have to login again

**Comment by johanlantz** [comment]
Do you provide a storage to the CognitoUserPool? There is a good example on how to do that here:
https://pub.dev/packages/amazon_cognito_identity_dart

under use custom storage.

By default things are just persisted in memory.
