### ISSUE TITLE
how to input a new password when signin with a temporary password  

### ISSUE THREAD

**Issue by zhangli-jerry** [jonsaw/amazon-cognito-identity-dart#69]
when i signin with  a temporary password  ,the cognito require a new password to complete the flow. 

how to complete new password challenge?

thanks

**Comment by chetanregmi-s2g** [comment]
https://github.com/chetanregmi-s2g/amazon-cognito-identity-dart

**Comment by zhangli-jerry** [comment]
> https://github.com/chetanregmi-s2g/amazon-cognito-identity-dart

Thanks very much.
